spring:
  application:
    name: blogpost

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  datasource:
    url: jdbc:h2:file:./.data/blogpost
    username: username
    password: password
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    de.raywo_trainings: WARN

cors:
  allow:
    origins: ${CORS_ALLOWED_ORIGINS:*}
    credentials: ${CORS_ALLOW_CREDENTIALS:false}
    headers: ${CORS_ALLOWED_HEADERS:[]}
